// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_product_lastpurchaserate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_product_lastpurchaserate));
        
        string IMigrationMetadata.Id
        {
            get { return "201305070815394_mig_product_lastpurchaserate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
