// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201305280443035_mig_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
