// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_so_validate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_so_validate));
        
        string IMigrationMetadata.Id
        {
            get { return "201304270836532_mig_so_validate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
