// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_pi_amonut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_pi_amonut));
        
        string IMigrationMetadata.Id
        {
            get { return "201306130609500_mig_pi_amonut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
