// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_sublocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_sublocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201305101329264_mig_sublocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
