// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_version));
        
        string IMigrationMetadata.Id
        {
            get { return "201305291427301_mig_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
