// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_packinglist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_packinglist));
        
        string IMigrationMetadata.Id
        {
            get { return "201305021245419_mig_packinglist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
