// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_salesorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_salesorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201304230154141_mig_salesorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
