// <auto-generated />
namespace b.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_saleschange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_saleschange));
        
        string IMigrationMetadata.Id
        {
            get { return "201304240437128_mig_saleschange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
